name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pegando o seu código
        uses: actions/checkout@v4

      - name: Preparando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Preparando o Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalando o Flet
        run: pip install flet

      - name: Construindo o APK
        run: flet build apk

      - name: Gerando link de Download
        uses: actions/upload-artifact@v4
        with:
          name: App-Heatmap-APK
          path: build/apk/**/*.apk
